feat(scripts/examples/azure/docker/az-config): validate options

diff --git a/scripts/examples/azure/docker/az-config b/scripts/examples/azure/docker/az-config
--- a/scripts/examples/azure/docker/az-config
+++ b/scripts/examples/azure/docker/az-config
@@ -46,6 +46,12 @@ while [[ "${1}" =~ ^- && ! "${1}" == "--" ]]; do
       shift
       target_directory="${1}"
       ;;
+
+    * )
+      echo "Invalid option: ${1}"
+      show_usage
+      exit 1
+      ;;
   esac
   shift
 done
