refactor(scripts/examples/azure/docker/az-run): add option

diff --git a/scripts/examples/azure/docker/az-run b/scripts/examples/azure/docker/az-run
--- a/scripts/examples/azure/docker/az-run
+++ b/scripts/examples/azure/docker/az-run
@@ -79,6 +79,12 @@ while [[ "${1}" =~ ^- && ! "${1}" == "--" ]]; do
       debug_level="${1}"
       ;;
 
+    * )
+      echo "Invalid option: ${1}"
+      show_usage
+      exit 1
+      ;;
+
   esac
   shift
 done
